cookie:
  expiry_days: 30
  key: "t9d1ygha4suuy5mhjefykf69rzf1ek23"
  name: "Eve"
credentials:
  usernames:
    ecruanes:
      email: eve.cruanes@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Eve
      last_name: Cruanes
      logged_in: False # Will be managed automatically
      password: test # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: Rebecca
      last_name: Briggs
      logged_in: False # Will be managed automatically
      password: def # Will be hashed automatically
      roles: # Optional
      - viewer
